// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTgJEcuVQe6LaeO4OYsT6T8tRmTSUJik',
    appId: '1:288253242585:web:89b2be7fe3974fffe562c8',
    messagingSenderId: '288253242585',
    projectId: 'yozrkha-cos',
    authDomain: 'yozrkha-cos.firebaseapp.com',
    storageBucket: 'yozrkha-cos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CXw5qHQ-i5_1Jf5K4We3DSfheqfuF3g',
    appId: '1:288253242585:android:88086d3a9fa5a15be562c8',
    messagingSenderId: '288253242585',
    projectId: 'yozrkha-cos',
    storageBucket: 'yozrkha-cos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrn9rqfq9BvO77xPZeHnT0dr3RlXFtsYs',
    appId: '1:288253242585:ios:cbbe55eed334067de562c8',
    messagingSenderId: '288253242585',
    projectId: 'yozrkha-cos',
    storageBucket: 'yozrkha-cos.appspot.com',
    iosBundleId: 'com.example.yorzkhaCos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrn9rqfq9BvO77xPZeHnT0dr3RlXFtsYs',
    appId: '1:288253242585:ios:9f9e88ca3e1de713e562c8',
    messagingSenderId: '288253242585',
    projectId: 'yozrkha-cos',
    storageBucket: 'yozrkha-cos.appspot.com',
    iosBundleId: 'com.example.yorzkhaCos.RunnerTests',
  );
}
